### ISSUE TITLE
misleading typo

### ISSUE THREAD

**Issue by climatebrad** [learn-co-curriculum/dsc-project-building-a-calculator#3]
"float" should be "floor"

> Change the code in the division function so that if a user selects division operation, the code should ask the user if he/she wants a normal division `/` or float division `//`, or a modulo division `%` which only returns the remainder of a division. The program should return an exception for any other inputs.

should be

> Change the code in the division function so that if a user selects division operation, the code should ask the user if he/she wants a normal division `/` or floor division `//`, or a modulo division `%` which only returns the remainder of a division. The program should return an exception for any other inputs.

**Comment by sumedh10** [comment]
Thanks, fixed.
